version: '3'
services:
  app:
    container_name: docker-urlshortner
    image: akhiljns/urlshortner:v1
    build: .
    links:
      - redis
    ports:
      - "10095:10095"
    volumes:
      - ~/docker/redis:/urlshortner/logs
  redis:
    container_name: docker-redis
    image: akhiljns/redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"
